# Generated by Django 4.0.2 on 2022-02-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_apptimeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedWebTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=10)),
                ('slot_id', models.CharField(max_length=10)),
            ],
        ),
    ]
