# Generated by Django 4.0.2 on 2022-02-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_bookedwebtimeslots_scheduled_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedAppTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=10)),
                ('slot_id', models.CharField(max_length=10)),
                ('scheduled_Date', models.DateField(null=True)),
                ('scheduled_Time', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
