# Generated by Django 4.0.2 on 2022-02-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_bookedapptimeslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedapptimeslots',
            name='client_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookedapptimeslots',
            name='client_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookedapptimeslots',
            name='client_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookedwebtimeslots',
            name='client_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookedwebtimeslots',
            name='client_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookedwebtimeslots',
            name='client_phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
